apache/carbondata

- README.md
Update README as per Apache glossary
> Update README as per Apache glossary

- integration/spark/src/main/java/org/carbondata/spark/load/CarbonLoaderUtil.java
When loading the multiple times and the store path is relative then the old segment folders are deleted.
The defect is able to reproduce when the store path is relative path, but I am not able to reproduce the issue when the store path is hdfs as mentioned in the jira issue.
https://issues.apache.org/jira/browse/CARBONDATA-44
> [CARBONDATA-44]Segment folders are deleted for multiple loads

- integration/spark/src/main/scala/org/apache/spark/sql/CarbonCatalystOperators.scala
- integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
- integration/spark/src/main/scala/org/apache/spark/sql/catalyst/CarbonTableIdentifierImplicit.scala
- integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
- integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonStrategies.scala
describe formatted command is failing from thrift server. This PR fixes it.
https://issues.apache.org/jira/browse/CARBONDATA-147
> [CARBONDATA-147]Fixed describe formatted issue

- integration/spark/src/test/scala/org/apache/carbondata/spark/testsuite/aggquery/AllDataTypesTestCaseAggregate.scala
- integration/spark/src/test/scala/org/apache/carbondata/spark/testsuite/filterexpr/FilterProcessorTestCase.scala
In this PR, DROP TABLE is added in all test cases.
> [CARBONDATA-209] add DROP TABLE in all test cases

- integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
**Why raise this pr?**
Currently we are displaying Unsupported feature aggregate table info in describe formatted command description
**How to resolve?**
Remove  aggregate table info from describe formatted command description
> [CARBONDATA-228] Removed Unsupported features from describe formatted command description

- README.md
> Add cluster deployment guide

- integration-testcases/pom.xml
Updated integration-test/pom.xml with correct version
> Updated integration-test/pom.xml with correct version

- core/src/main/java/org/apache/carbondata/scan/expression/logical/FalseExpression.java
Add license header for FalseExpression.java
> Add license header for FalseExpression.java

- integration/spark/src/main/scala/org/apache/carbondata/spark/util/GlobalDictionaryUtil.scala
fix jira issue carbondata-339, replace hdfsLocation with storePath in the function generateGlobalDictionary
https://issues.apache.org/jira/browse/CARBONDATA-339
> [carbondata-339] Align storePath name in generateGlobalDictionary() of GlobalDictionaryUtil.scala

- docs/DML-Operations-on-Carbon.md
Update doc for dateformat option
http://136.243.101.176:8080/job/ApacheCarbonManualPRBuilder/535/
> [CARBONDATA-353]Update doc for dateformat option

- integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonMetastoreCatalog.scala
Problem:
1. Whenever a catalog metadata is refreshed it modified the timestamp of modifiedTime.mdt file which leads to unnecessary refreshing the complete catalog metadata.
2. Array Index of bound exception is thrown on failure of table creation.
Analysis:
1. Whenever carbon environment gets initialized it loads the table metadata in the catalog and changes the timestamp of modifiedTime.mdt file. If a parallel beeline session is in progress then it will cause unnecessary refreshing of the catalog metadata.
2. For the very first time if table creation fails then in the exception block it tries to drop that table and clear its metadata. In drop table filter API is used which throws array index out of bound exception if metadata array is empty.
Fix:
1. No need to update the timestamp of …
> [CARBONDATA-381] Unnecessary catalog metadata refresh and array index of bound exception in drop table

- hadoop/src/main/java/org/apache/carbondata/hadoop/CarbonInputSplit.java
- hadoop/src/main/java/org/apache/carbondata/hadoop/api/CarbonTableInputFormat.java
- hadoop/src/main/java/org/apache/carbondata/hadoop/api/CarbonTableOutputCommitter.java
- hadoop/src/main/java/org/apache/carbondata/hadoop/internal/CarbonInputSplit.java
- hadoop/src/main/java/org/apache/carbondata/hadoop/internal/index/Index.java
- hadoop/src/main/java/org/apache/carbondata/hadoop/internal/index/IndexLoader.java
- hadoop/src/main/java/org/apache/carbondata/hadoop/internal/index/impl/InMemoryBTreeIndex.java
- hadoop/src/main/java/org/apache/carbondata/hadoop/internal/index/impl/InMemoryBTreeIndexLoader.java
- hadoop/src/main/java/org/apache/carbondata/hadoop/internal/segment/Segment.java
- hadoop/src/main/java/org/apache/carbondata/hadoop/internal/segment/SegmentManager.java
- hadoop/src/main/java/org/apache/carbondata/hadoop/internal/segment/impl/IndexedSegment.java
This PR fixes the compilation and check style issues of https://github.com/apache/incubator-carbondata/pull/208
> [CARBONDATA-284]Fixed compilation and checkstyle issues of PR 208

- README.md
Update readme as per IPMC comments:
1.Adds incubating.
2.Removes the original contributed company.
> Update readme as per IPMC comments

- core/src/main/java/org/apache/carbondata/core/reader/CarbonDictionaryMetadataReaderImpl.java
- core/src/main/java/org/apache/carbondata/core/reader/CarbonDictionaryReaderImpl.java
- core/src/main/java/org/apache/carbondata/core/reader/sortindex/CarbonDictionarySortIndexReaderImpl.java
- core/src/main/java/org/apache/carbondata/core/writer/CarbonDictionaryWriterImpl.java
- core/src/test/java/org/apache/carbondata/core/reader/sortindex/CarbonDictionarySortIndexReaderImplTest.java
- core/src/test/java/org/apache/carbondata/core/writer/sortindex/CarbonDictionarySortIndexWriterImplTest.java
- integration/spark/src/main/java/org/apache/carbondata/spark/load/CarbonLoaderUtil.java
- integration/spark/src/main/scala/org/apache/carbondata/spark/CarbonSparkFactory.scala
- integration/spark/src/main/scala/org/apache/carbondata/spark/DictionaryDetailHelper.scala
- integration/spark/src/main/scala/org/apache/carbondata/spark/rdd/CarbonDataLoadRDD.scala
- integration/spark/src/main/scala/org/apache/carbondata/spark/rdd/CarbonDataRDDFactory.scala
- integration/spark/src/main/scala/org/apache/carbondata/spark/rdd/CarbonDeleteLoadByDateRDD.scala
- integration/spark/src/main/scala/org/apache/carbondata/spark/rdd/CarbonMergerRDD.scala
- integration/spark/src/main/scala/org/apache/carbondata/spark/rdd/Compactor.scala
- integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
change parameters' name from hdfsStoreLocation/hdfsStorePath to storePath in order to avoid ambiguity.
> [CARBONDATA-383]Optimize hdfsStoreLocation/hdfsStorePath parameters' name since Carbon not only support hdfs path

- examples/src/main/scala/org/apache/carbondata/examples/CarbonExample.scala
Fix codestyle in CarbonExample
> Fix codestyle in CarbonExample

- assembly/pom.xml
- common/pom.xml
- core/pom.xml
- examples/pom.xml
- format/pom.xml
- hadoop/pom.xml
- integration-testcases/pom.xml
- integration/spark/pom.xml
- pom.xml
- processing/pom.xml
In branch-0.2, the next version number should be 0.2.1
> update pom version

- assembly/pom.xml
- common/pom.xml
- core/pom.xml
- examples/pom.xml
- format/pom.xml
- hadoop/pom.xml
- integration-testcases/pom.xml
- integration/spark/pom.xml
- pom.xml
- processing/pom.xml
0.2.0 already released,update pom version to 0.3.0
> update pom version to 0.3.0

- core/src/test/java/org/apache/carbondata/core/cache/dictionary/ReverseDictionaryCacheTest.java
- integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
- integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
- integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonMetastoreCatalog.scala
> [CARBONDATA-462] Clean up carbonTableSchema.scala before moving to spark-common module

- integration/spark-common/src/main/scala/org/apache/carbondata/spark/rdd/CarbonDataLoadRDD.scala
Fix a insertinto bug for reading from hive table concurrently
> [CARBONDATA-486]fix bug for reading dataframe concurrently

- integration/spark-common/pom.xml
correct pom dependency for spark2 integration
> [SPARK2] exclude dependency

- examples/spark/src/main/scala/org/apache/carbondata/examples/DirectSQLExample.scala
> Correct DirectSQLExample name

- integration/spark2/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
For spark2, GlobalDictionaryUtil.updateTableMetadataFunc should been initialized
> [CARBONDATA-536]initialize updateTableMetadata method in LoadTable for Spark2

- core/src/main/java/org/apache/carbondata/core/constants/CarbonCommonConstants.java
Remove unused code for CarbonCommonConstants.java
> Remove unused code for CarbonCommonConstants.java

- README.md
add website link http://carbondata.incubator.apache.org
> Add website link in readme

- examples/spark2/src/main/scala/org/apache/carbondata/examples/SparkSessionExample.scala
Add spark.stop for SparkSessionExample
> Add spark.stop for SparkSessionExample

- build/README.md
> Update to support spark2.1

- README.md
Add CI building status and Apaches license icon
> Add CI building status and Apaches license icon

- core/src/main/java/org/apache/carbondata/core/cache/dictionary/DoubleArrayTrieDictionary.java
- integration/spark-common-test/pom.xml
1. now the profile spark-1.6 should be active by default. 
2. recover DoubleArrayTrieDictionary.java
> fix default profile for spark-common-test

- core/src/main/java/org/apache/carbondata/core/constants/CarbonCommonConstants.java
- core/src/main/java/org/apache/carbondata/core/datastore/compression/ReaderCompressModel.java
- core/src/main/java/org/apache/carbondata/core/metadata/ValueEncoderMeta.java
- core/src/main/java/org/apache/carbondata/core/util/CarbonMetadataUtil.java
- core/src/main/java/org/apache/carbondata/core/util/CarbonUtil.java
- core/src/main/java/org/apache/carbondata/core/util/ValueCompressionUtil.java
- core/src/main/java/org/apache/carbondata/core/util/path/CarbonTablePath.java
- core/src/test/java/org/apache/carbondata/core/datastore/SegmentTaskIndexStoreTest.java
- core/src/test/java/org/apache/carbondata/core/util/CarbonMetadataUtilTest.java
- core/src/test/java/org/apache/carbondata/core/util/DataTypeUtilTest.java
- core/src/test/java/org/apache/carbondata/core/util/ValueCompressionUtilTest.java
Problem: Query is not working with old store
Solution: As big decimal compression is added in new flow we need to add  handle old store
> [CARBONDATA-674]Fixed Compatibility issue

- core/src/main/java/org/apache/carbondata/core/scan/result/iterator/VectorDetailQueryResultIterator.java
- core/src/main/java/org/apache/carbondata/core/statusmanager/SegmentStatusManager.java
To clean some code：
1. Correct the spelling mistake
2. Remove unused function
3. Iterate the Array instead of transform it to List.
I will raise a jira when my net is stable.
> [CARBONDATA-676] Code clean

- core/src/main/java/org/apache/carbondata/core/keygenerator/columnar/impl/MultiDimKeyVarLengthEquiSplitGenerator.java
- core/src/main/java/org/apache/carbondata/core/reader/CarbonDeleteDeltaFileReaderImpl.java
- core/src/main/java/org/apache/carbondata/core/scan/expression/ExpressionResult.java
- core/src/main/java/org/apache/carbondata/core/scan/result/AbstractScannedResult.java
- core/src/main/java/org/apache/carbondata/core/scan/result/impl/FilterQueryScannedResult.java
- core/src/main/java/org/apache/carbondata/core/scan/result/impl/NonFilterQueryScannedResult.java
- core/src/main/java/org/apache/carbondata/core/util/ValueCompressionUtil.java
- core/src/test/java/org/apache/carbondata/core/util/ValueCompressionUtilTest.java
cleanup un-exercised code/field/functions as well as minor fix.
> [CARBONDATA-661] misc cleanup in carbon core

- integration/spark-common-test/src/test/scala/org/apache/carbondata/integration/spark/testsuite/primitiveTypes/FloatDataTypeTestCase.scala
- integration/spark-common-test/src/test/scala/org/apache/carbondata/spark/testsuite/datetype/DateTypeTest.scala
> [CARBONDATA-682] Added License to FloatDataTypeTestCase.scala and DateTypeTest.scala

- assembly/pom.xml
- common/pom.xml
- core/pom.xml
- examples/flink/pom.xml
- examples/spark/pom.xml
- examples/spark2/pom.xml
- format/pom.xml
- hadoop/pom.xml
- integration/spark-common-test/pom.xml
- integration/spark-common/pom.xml
- integration/spark/pom.xml
- integration/spark2/pom.xml
- pom.xml
- processing/pom.xml
Upgrade pom version of master to 1.1.0.
Passed test with command: mvn clean -Pbuild-with-format -Pspark-1.6 install.
> Upgrade pom version of master to 1.1.0

- NOTICE
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:
`[CARBONDATA-<Jira issue #>] Description of pull request`
Travis-CI on your fork and ensure the whole test matrix passes).
number, if there is one.
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).
Please provide details on 
- Whether new unit test cases have been added or why no new tests are required?
- What manual testing you have done?
- Any additional information to help reviewers in testing this change.
---
> [CARBONDATA-686] Extend period coverage in NOTICE

- core/src/main/java/org/apache/carbondata/core/cache/dictionary/ForwardDictionaryCache.java
**Problem:**
Currently when more than 1 task is getting launched in one node for a query both the task is trying to load the dictionary data and its impacting dictionary loading performance.
**Solution:**
Need to add monitor for dictionary loading one task will load the dictionary and other task will be waiting and share the same dictionary data
> [CARBONDATA-735]Dictionary performance issue with multiple task in same executor

- pom.xml
> Quick fix of style in pom.xml

- docs/How-to-contribute-to-Apache-CarbonData.md
Add Git config for how to contribution guide:
$ git config --global user.email "you@example.com"
$ git config --global user.name "Your Name"
> Add Git config for how to contribution guide

- integration/spark2/src/main/scala/org/apache/spark/sql/CarbonDictionaryDecoder.scala
fix dictionary decode code gen compile error
> Fix compilation for codegen

- core/src/main/java/org/apache/carbondata/core/scan/processor/AbstractDataBlockIterator.java
- core/src/main/java/org/apache/carbondata/core/scan/processor/impl/DataBlockIteratorImpl.java
- core/src/main/java/org/apache/carbondata/core/scan/result/AbstractScannedResult.java
- core/src/main/java/org/apache/carbondata/core/scan/result/iterator/AbstractDetailQueryResultIterator.java
- core/src/main/java/org/apache/carbondata/core/scan/scanner/AbstractBlockletScanner.java
- core/src/main/java/org/apache/carbondata/core/scan/scanner/impl/FilterScanner.java
- core/src/main/java/org/apache/carbondata/core/stats/QueryStatisticsConstants.java
- core/src/main/java/org/apache/carbondata/core/stats/QueryStatisticsRecorderImpl.java
- core/src/main/java/org/apache/carbondata/core/util/BitSetGroup.java
- processing/src/main/java/org/apache/carbondata/processing/store/writer/v3/CarbonFactDataWriterImplV3.java
**Problem**: Memory leak during off heap query + added statistics for V3 during query
**Solution**: In data Block iterator need to free memory for occupied during query
Added statistics for V3 format(Number of valid pages and total number of pages)
> [CARBONDATA-787] Fixed memory leak in offhep during query

- core/src/main/java/org/apache/carbondata/core/scan/collector/impl/AbstractScannedResultCollector.java
- core/src/main/java/org/apache/carbondata/core/scan/collector/impl/DictionaryBasedResultCollector.java
- core/src/main/java/org/apache/carbondata/core/scan/collector/impl/RawBasedResultCollector.java
- core/src/main/java/org/apache/carbondata/core/scan/collector/impl/RestructureBasedDictionaryResultCollector.java
- core/src/main/java/org/apache/carbondata/core/scan/collector/impl/RestructureBasedRawResultCollector.java
- core/src/main/java/org/apache/carbondata/core/scan/result/AbstractScannedResult.java
- core/src/main/java/org/apache/carbondata/core/scan/result/impl/FilterQueryScannedResult.java
- core/src/main/java/org/apache/carbondata/core/scan/result/impl/NonFilterQueryScannedResult.java
- core/src/test/java/org/apache/carbondata/core/scan/result/impl/FilterQueryScannedResultTest.java
- core/src/test/java/org/apache/carbondata/core/scan/result/impl/NonFilterQueryScannedResultTest.java
[CARBONDATA-799] change word from currenr to current
> [CARBONDATA-799] change word from currenr to current

- integration/spark-common/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
- integration/spark2/src/main/scala/org/apache/spark/sql/parser/CarbonSpark2SqlParser.scala
If user does not provide default value in add column, dictionary & sort index file will not be created which is throwing exception while querying. Current change will create dictionary file with default null value if not default value is provided in add column query
> [CARBONDATA-802]Select query is throwing exception when newly column is added without any default value

- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataMetadata.java
Changed the way the Metadata was getting created used column schema instead of dimensions and measure seperately.
> [CARBONDATA-834] Fixed Describe Table for Presto

- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataColumnHandle.java
- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataMetadata.java
- integration/presto/src/main/java/org/apache/carbondata/presto/impl/CarbonLocalInputSplit.java
- integration/presto/src/main/java/org/apache/carbondata/presto/impl/CarbonTableConfig.java
- integration/presto/src/main/java/org/apache/carbondata/presto/impl/CarbonTableReader.java
Fix typo issues of integration/ presto
> Fix typo issues of integration/ presto

- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataConnectorFactory.java
- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataMetadata.java
- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataRecordSetProvider.java
- integration/presto/src/main/java/org/apache/carbondata/presto/impl/CarbonTableReader.java
Refactor integration/presto by optimizing some name definition.
> Refactor integration/presto by optimizing some name definition

- docs/quick-start-guide.md
Documentation : Added details of assembly jar in Quick Start guide
> [CARBONDATA-884] Assembly jar information in Quick Start guide

- integration/spark2/src/test/scala/org/apache/spark/carbondata/restructure/AlterTableRevertTestCase.scala
- integration/spark2/src/test/scala/org/apache/spark/carbondata/restructure/AlterTableValidationTestCase.scala
- integration/spark2/src/test/scala/org/apache/spark/carbondata/restructure/rowreader/AddColumnTestCases.scala
- integration/spark2/src/test/scala/org/apache/spark/carbondata/restructure/rowreader/ChangeDataTypeTestCases.scala
- integration/spark2/src/test/scala/org/apache/spark/carbondata/restructure/rowreader/DropColumnTestCases.scala
- processing/src/test/java/org/apache/carbondata/lcm/locks/LocalFileLockTest.java
[CARBONDATA-891] Fix compilation issue of LocalFileLockTest generate new folder "carbon.store"
> [CARBONDATA-891] Fix compilation issue of LocalFileLockTest generate new folder "carbon.store"

- README.md
Added a link to configuration parameters on the main page of doc
> [CARBONDATA-928] Added a link to configuration parameters in doc

- core/src/main/java/org/apache/carbondata/core/metadata/AbsoluteTableIdentifier.java
- integration/spark2/src/main/scala/org/apache/spark/sql/hive/CarbonHiveMetadataUtil.scala
- integration/spark2/src/test/scala/org/apache/spark/carbondata/deletetable/DeleteTableTestCase.scala
problem : Create table IS (table name)
drop table IS throwing exception
Solution : use hive drop table to delete hive table from hive metastore
> [CARBONDATA-930] Drop table IS throwing exception

- integration/spark-common-test/src/test/scala/org/apache/carbondata/spark/testsuite/dataload/TestLoadDataFrame.scala
- integration/spark/src/main/scala/org/apache/carbondata/spark/CarbonDataFrameWriter.scala
Added single pass load option  in data frame writer ( spark 1.6 )
Tested with HDP 2.5 / Spark 1.6
> [CARBONDATA-909] Added option to specify single pass load in data frame

- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataColumnHandle.java
- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataConnector.java
- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataConnectorFactory.java
- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataMetadata.java
- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataModule.java
- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataPageSource.java
- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataPageSourceProvider.java
- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataRecordCursor.java
- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataRecordSet.java
- integration/presto/src/main/java/org/apache/carbondata/presto/CarbondataRecordSetProvider.java
Added Support for DecimalType and Timestamp with Spark-2.1
Local Build is running fine.
Manually Tested the functionality on Presto CLI
> [CARBONDATA-899] Added Support for DecimalType and Timestamp for spark-2.1

- integration/spark2/src/test/scala/org/apache/spark/carbondata/restructure/rowreader/AddColumnTestCases.scala
- processing/src/main/java/org/apache/carbondata/processing/merger/CompactionResultSortProcessor.java
After load if new column added to the table and minor compaction has been performed .
Then new column contains null value by default or if bad_record exists . And cast should not done with null value.
> [CARBONDATA-949] null value handled during compaction

- integration/spark-common/src/main/scala/org/apache/carbondata/spark/rdd/AlterTableAddColumnRDD.scala
Added HDFS lock to handle concurrent queries in executor side
> [CARBONDATA-972] Concurrent add columns query fails

- hadoop/src/main/java/org/apache/carbondata/hadoop/CarbonInputFormat.java
problem: After clean files DDL is run, the blocks which are deleted are also getting in getSplits() of CarbonScanRDD.scala
Solution: when the segments index map is created in carbonInputFormat.scala , get only the valid tasks which contain the valid blocks
> [CARBONDATA-970] getSplits() from carbonScanRDD not ignoring the blocks which are cleared using clean files DDL

- docs/useful-tips-on-carbondata.md
Add docs for Optimizing Mass Data Loading in docs/useful-tips-on-carbondata.md . The same to "https://github.com/apache/incubator-carbondata/pull/806"
> docs-for-optimizing-mass-data-loading

- integration/spark-common-test/src/test/scala/org/apache/carbondata/spark/testsuite/detailquery/RangeFilterAllDataTypesTestCases.scala
Range filter test case is failing in current master, this PR fixes it.
> [CARBONDATA-1006] Range filter test fix

- integration/hive/src/main/java/org/apache/carbondata/hive/CarbonHiveRecordReader.java
This Pr Fixes Bug For Class Cast Exception When Selecting Date Data Type In hive from carbon table
- Resolved Bug For Class Cast Exception In hive
- Test It Manually using hive cli
> [CARBONDATA-950] Resolved Bug for Class Cast Exception When Selecting Date Type In hive

- integration/spark2/src/main/scala/org/apache/spark/sql/CarbonSource.scala
- integration/spark2/src/main/scala/org/apache/spark/sql/parser/CarbonSpark2SqlParser.scala
- integration/spark2/src/main/scala/org/apache/spark/sql/parser/CarbonSparkSqlParser.scala
- integration/spark2/src/test/scala/org/apache/spark/carbondata/CarbonDataSourceSuite.scala
Analysis: Earlier the flow to get TableModel was different for CarbonSource which cause the create table to fail in case of complex types.
> [CARBONDATA-1033] Fixed complex data type in CarbonSource

- README.md
> Update travins-ci link

- README.md
- docs/How-to-contribute-to-Apache-CarbonData.md
- docs/installation-guide.md
- docs/quick-start-guide.md
> [CARBONDATA-1044] Rename incubator-carbondata to carbondata in docs and readme.

- core/src/main/java/org/apache/carbondata/core/scan/expression/ExpressionResult.java
- core/src/main/java/org/apache/carbondata/core/scan/expression/conditional/NotInExpression.java
- core/src/main/java/org/apache/carbondata/core/scan/filter/executer/RowLevelRangeLessThanFiterExecuterImpl.java
Problem : Filter Test Case failure. 
a) Nullpointer Handling in Not Expression.
b) LessThan Filter Expression : Wrong calculation of StartKey for setting the Bits.
> [CARBONDATA-1070]Not In Filter Expression Null Value Handling

- integration/spark-common-test/src/test/scala/org/apache/carbondata/spark/testsuite/iud/DeleteCarbonTableTestCase.scala
- integration/spark2/src/main/scala/org/apache/spark/sql/optimizer/CarbonLateDecodeRule.scala
- integration/spark2/src/test/scala/org/apache/spark/carbondata/iud/DeleteCarbonTableSubqueryTestCase.scala
The reason is tupleid udf is not properly pushed down to the projection plan in case of join condition.
> [CARBONDATA-1189] Fixed delete with subquery issue

- core/src/main/java/org/apache/carbondata/core/scan/result/AbstractScannedResult.java
Handling multiple implicit columns
> [CARBONDATA-1194] Problem in filling/processing multiple implicit columns

- .asf.yaml
Enable github's merge function
- No
- No
- Yes
> Enable github's merge function

- README.md
- docs/how-to-contribute-to-apache-carbondata.md
Can't open the mail list, we should fixed it.
https://github.com/apache/carbondata/pull/4300
change the mail list address
- No
- No, only change the document
>  [ISSUE-4298] Fixed mail list issue

- integration/hive/pom.xml
There are some compile issue when compile carbondata latest master with spark2.3
https://github.com/apache/carbondata/issues/4299
fixed the compile issue
- No
- No, only change the dependency version
> [ISSUE-4299] Fixed compile issue with spark 2.3

- .gitignore
- examples/spark/src/main/java/org/apache/carbondata/examples/sdk/SDKS3ReadExample.java
There are some code style， which should be optimized
optimize the magic code in example 
- No
- No, only change the example
> [ISSUE-4305] Optimize the magic number

- sdk/sdk/src/main/java/org/apache/carbondata/sdk/file/CarbonWriterBuilder.java
- sdk/sdk/src/main/java/org/apache/carbondata/sdk/file/Schema.java
> [ISSUE-4305] Optimize the usage of equalsIgnoreCase, which can avoid NPE

- sdk/sdk/src/main/java/org/apache/carbondata/sdk/file/CarbonSchemaReader.java
- sdk/sdk/src/main/java/org/apache/carbondata/sdk/file/arrow/ArrowFieldWriter.java
There are some code style， which should be optimized
There are some code style， which should be optimized
- No
- No, There are some code style， which should be optimized
> [ISSUE-4305] Add @Override for override method

- examples/spark/src/main/java/org/apache/carbondata/examples/sdk/SDKS3ReadExample.java
- examples/spark/src/main/java/org/apache/carbondata/examples/sdk/SDKS3SchemaReadExample.java
- sdk/sdk/src/main/java/org/apache/carbondata/sdk/file/CarbonSchemaReader.java
Fix the issue when read schema from S3
There are some error when I run the SDKS3SchemaReadExample 
https://github.com/apache/carbondata/issues/4306
Fix the error of SDKS3SchemaReadExample
- No
- No, optimize the example
> [ISSUE-4306] Fix the error of SDKS3SchemaReadExample

- processing/src/main/java/org/apache/carbondata/processing/loading/BadRecordsLoggerProvider.java
- processing/src/main/java/org/apache/carbondata/processing/loading/model/CarbonLoadModelBuilder.java
- processing/src/main/java/org/apache/carbondata/processing/util/Auditor.java
- processing/src/main/java/org/apache/carbondata/processing/util/CarbonDataProcessorUtil.java
There are some code smells in processing module
For example
1.Didn't add @OverRide for override method
2.magic number
3.variable Should Use LowerCamelCase
variableShouldUseLowerCamelCase
- No
- No
> [ISSUE-4313] Variable should use LowerCamelCase style

- build/How-to-build-carbondata-notebook-docker-image-by-dockerfile.md
- build/How-to-build-carbondata-notebook-docker-image-by-manual.md
- build/README.md
- build/docker/carbondata-notebook/Dockerfile
Build carbondata notebook docker image by manual and by dockerfile
Build carbondata notebook docker image by manual and by dockerfile
- No
- No
> Build carbondata notebook docker image by manual and by dockerfile

- sdk/sdk/src/main/java/org/apache/carbondata/sdk/file/CarbonIUD.java
- sdk/sdk/src/main/java/org/apache/carbondata/sdk/file/CarbonSchemaReader.java
- sdk/sdk/src/main/java/org/apache/carbondata/sdk/file/TestUtil.java
- sdk/sdk/src/main/java/org/apache/carbondata/sdk/file/arrow/ArrowConverter.java
- sdk/sdk/src/main/java/org/apache/carbondata/sdk/file/arrow/ArrowUtils.java
- sdk/sdk/src/main/java/org/apache/carbondata/sdk/file/arrow/ArrowWriter.java
- sdk/sdk/src/test/java/org/apache/carbondata/sdk/file/ArrowCarbonReaderTest.java
CONSTANTS should be like: UPPER_NAME;
variable should be lowerCamelCase
CONSTANTS should be like: UPPER_NAME;
variable should be lowerCamelCase
- No
- No
> [ISSUE-4305] Optimize the constants and variable style

- processing/src/main/java/org/apache/carbondata/processing/exception/SliceMergerException.java
- processing/src/main/java/org/apache/carbondata/processing/loading/csvinput/BlockDetails.java
- processing/src/main/java/org/apache/carbondata/processing/loading/exception/BadRecordFoundException.java
- processing/src/main/java/org/apache/carbondata/processing/loading/exception/CarbonDataLoadingException.java
- processing/src/main/java/org/apache/carbondata/processing/loading/exception/NoRetryException.java
- processing/src/main/java/org/apache/carbondata/processing/loading/partition/impl/HashPartitionerImpl.java
- processing/src/main/java/org/apache/carbondata/processing/loading/partition/impl/SparkHashExpressionPartitionerImpl.java
- processing/src/main/java/org/apache/carbondata/processing/loading/sort/unsafe/comparator/UnsafeRowComparator.java
- processing/src/main/java/org/apache/carbondata/processing/loading/sort/unsafe/comparator/UnsafeRowComparatorForNormalDims.java
- processing/src/main/java/org/apache/carbondata/processing/loading/sort/unsafe/holder/UnsafeFinalMergePageHolder.java
- processing/src/main/java/org/apache/carbondata/processing/loading/sort/unsafe/holder/UnsafeInmemoryHolder.java
- processing/src/main/java/org/apache/carbondata/processing/loading/sort/unsafe/holder/UnsafeSortTempFileChunkHolder.java
- processing/src/main/java/org/apache/carbondata/processing/loading/sort/unsafe/merger/UnsafeSingleThreadFinalSortFilesMerger.java
- processing/src/main/java/org/apache/carbondata/processing/merger/CompactionResultSortProcessor.java
- processing/src/main/java/org/apache/carbondata/processing/merger/RowResultMergerProcessor.java
- processing/src/main/java/org/apache/carbondata/processing/sort/exception/CarbonSortKeyAndGroupByException.java
- processing/src/main/java/org/apache/carbondata/processing/sort/sortdata/InMemorySortTempChunkHolder.java
- processing/src/main/java/org/apache/carbondata/processing/sort/sortdata/IntermediateSortTempRowComparator.java
- processing/src/main/java/org/apache/carbondata/processing/sort/sortdata/NewRowComparator.java
- processing/src/main/java/org/apache/carbondata/processing/sort/sortdata/NewRowComparatorForNormalDims.java
- processing/src/main/java/org/apache/carbondata/processing/sort/sortdata/SingleThreadFinalSortFilesMerger.java
- processing/src/main/java/org/apache/carbondata/processing/store/CarbonFactDataHandlerColumnar.java
- processing/src/main/java/org/apache/carbondata/processing/store/writer/AbstractFactDataWriter.java
- processing/src/main/java/org/apache/carbondata/processing/store/writer/v3/CarbonFactDataWriterImplV3.java
There are some code smells in processing module
For example
1.Didn't add @OverRide for override method
2.magic number
https://github.com/apache/carbondata/issues/4313
Add @Override for override method of processing module
- No
- No, only Add @Override for override method of processing module
> [ISSUE-4313] Add @Override for override method of processing module

- integration/presto/src/main/java/org/apache/carbondata/presto/impl/CarbonLocalInputSplit.java
- integration/presto/src/main/prestodb/org/apache/carbondata/presto/CarbondataConnectorFactory.java
- integration/presto/src/main/prestodb/org/apache/carbondata/presto/CarbondataPageSourceProvider.java
- integration/presto/src/main/prestosql/org/apache/carbondata/presto/CarbondataConnectorFactory.java
- integration/presto/src/main/prestosql/org/apache/carbondata/presto/CarbondataPageSourceProvider.java
There are some code smells in presto module
For example
1.Didn't add @OverRide for override method
2.magic number
3.variable Should Use LowerCamelCase
optimize code smell in presto module
- No
- No
> optimize code smell in presto module

- integration/spark/src/main/java/org/apache/carbondata/spark/vectorreader/VectorizedCarbonRecordReader.java
- integration/spark/src/main/java/org/apache/carbondata/stream/CarbonStreamRecordReader.java
- integration/spark/src/main/java/org/apache/spark/sql/CarbonVectorProxy.java
- integration/spark/src/main/java/org/apache/spark/sql/secondaryindex/jobs/CarbonBlockLoaderHelper.java
- integration/spark/src/main/java/org/apache/spark/sql/secondaryindex/load/CarbonInternalLoaderUtil.java
- integration/spark/src/main/java/org/apache/spark/sql/secondaryindex/load/RowComparator.java
- integration/spark/src/main/scala/org/apache/carbondata/index/secondary/SecondaryIndex.java
- integration/spark/src/main/scala/org/apache/spark/sql/index/CarbonIndexUtil.scala
- integration/spark/src/main/scala/org/apache/spark/sql/secondaryindex/command/SICreationCommand.scala
There are some code smells in spark module
optimzie the some code smell 
- No
- No
> optimizeCodeSmellInSpark

- streaming/src/main/java/org/apache/carbondata/streaming/CarbonStreamOutputFormat.java
some code smells in streaming module 
some code smells in streaming module 
- No
- No
> optimize code smell in streaming module

- examples/spark/pom.xml
- index/secondary-index/pom.xml
- integration/flink/pom.xml
- integration/hive/src/test/java/org/apache/carbondata/hive/HiveCarbonTest.java
- integration/spark/pom.xml
- integration/spark/src/test/scala/org/apache/carbondata/spark/testsuite/datacompaction/MajorCompactionStopsAfterCompaction.scala
- integration/spark/src/test/scala/org/apache/carbondata/spark/testsuite/dataload/TestLoadDataFrame.scala
- integration/spark/src/test/scala/org/apache/carbondata/spark/testsuite/iud/TestInsertAndOtherCommandConcurrent.scala
- integration/spark/src/test/scala/org/apache/carbondata/view/rewrite/Tpcds_1_4_Suite.scala
- mv/plan/pom.xml
- pom.xml
- streaming/pom.xml
1. TestInsertAndOtherCommandConcurrent  testcase not working
2. After testing, there are many garbage files under project folder
1. Fix TestInsertAndOtherCommandConcurrent testcasee issue
3. Using a proper target path in testcase to avoid generating new files during test
4. Enable spark-2.4 by default
- No 
- Yes, enable 4 testcases
> Fix TestInsertAndOtherCommandConcurrent testcasee issue and enble testcase

- integration/spark/src/test/scala/org/apache/carbondata/spark/testsuite/directdictionary/TimestampDataTypeDirectDictionaryTestCase.scala
- sdk/sdk/src/main/java/org/apache/carbondata/sdk/file/CarbonSchemaReader.java
There is a checkstyle issue in sdk module
not import static method in CarbonSchemaReader
- No
- No
> [ISSUE-4338] Fix checkstyle issue in sdk module

- core/src/main/java/org/apache/carbondata/core/index/IndexStoreManager.java
- core/src/main/java/org/apache/carbondata/core/index/TableIndex.java
- core/src/main/java/org/apache/carbondata/core/index/dev/IndexFactory.java
- integration/spark/src/test/scala/org/apache/carbondata/view/rewrite/MVCreateTestCase.scala
- sdk/sdk/src/main/java/org/apache/carbondata/sdk/file/CarbonWriterBuilder.java
There are test case errors
1. update index schema of index cache
2. change mv name in testcase to avoid name confliction
- No 
- No
> [ISSUE-4342] Fix test case errors

- README.md
- docs/zh_cn/CarbonData典型应用场景之明细数据查询：点查+过滤条件.md
- pom.xml
It'd be better to use HTTPS for the website link instead of HTTP.  
Change HTTP to HTTPS in pom.xml and README
- No
- No
> Use https link instead of http

- build/README.md
The build document should be updated to reflect the thrift version update
/build/README is updated
- No
- No
> [CARBONDATA-4350] Update document for thrift version

- pom.xml
Update presto dependency version to 0.291 as per (https://prestodb.io/docs/current/)
- No
- No
- Yes
> Update presto dependency version to 0.291

- integration/spark/src/test/scala/org/apache/carbondata/spark/testsuite/index/CGIndexTestCase.scala
- integration/spark/src/test/scala/org/apache/carbondata/spark/testsuite/index/FGIndexTestCase.scala
- pom.xml
ByteOutputStream is not supported in com.sun.xml.internal package in new JDK version
Fix testcases
- No
- No
> [HOTFIX] Fix outdated packages

- README.md
Expanded on the AI-native data storage capabilities and challenges in data preparation for CarbonData.
- No
- No
- Yes
> Enhance README with AI-native data storage details
