apache/carbondata

core/src/main/java/org/carbondata/core/cache/dictionary/ColumnDictionaryInfo.java
core/src/main/java/org/carbondata/core/carbon/metadata/converter/ThriftWrapperSchemaConverterImpl.java
core/src/main/java/org/carbondata/core/carbon/metadata/datatype/DataType.java
core/src/main/java/org/carbondata/core/constants/CarbonCommonConstants.java
core/src/main/java/org/carbondata/core/util/DataFileFooterConverter.java
core/src/main/java/org/carbondata/core/util/DataTypeUtil.java
core/src/main/java/org/carbondata/core/writer/sortindex/CarbonDictionarySortModel.java
core/src/main/java/org/carbondata/scan/expression/DataType.java
core/src/main/java/org/carbondata/scan/expression/ExpressionResult.java
core/src/main/java/org/carbondata/scan/expression/arithmetic/AddExpression.java
core/src/main/java/org/carbondata/scan/expression/arithmetic/DivideExpression.java
core/src/main/java/org/carbondata/scan/expression/arithmetic/MultiplyExpression.java
core/src/main/java/org/carbondata/scan/expression/arithmetic/SubstractExpression.java
core/src/main/java/org/carbondata/scan/expression/conditional/EqualToExpression.java
core/src/main/java/org/carbondata/scan/expression/conditional/GreaterThanEqualToExpression.java
core/src/main/java/org/carbondata/scan/expression/conditional/GreaterThanExpression.java
core/src/main/java/org/carbondata/scan/expression/conditional/InExpression.java
core/src/main/java/org/carbondata/scan/expression/conditional/LessThanEqualToExpression.java
core/src/main/java/org/carbondata/scan/expression/conditional/LessThanExpression.java
core/src/main/java/org/carbondata/scan/expression/conditional/NotEqualsExpression.java
core/src/main/java/org/carbondata/scan/expression/conditional/NotInExpression.java
core/src/main/java/org/carbondata/scan/filter/FilterUtil.java
core/src/main/java/org/carbondata/scan/util/DataTypeUtil.java
format/src/main/thrift/schema.thrift
integration/spark/src/main/scala/org/apache/spark/sql/CarbonDatasourceRelation.scala
integration/spark/src/main/scala/org/apache/spark/sql/CarbonDictionaryDecoder.scala
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonMetastoreCatalog.scala
integration/spark/src/main/scala/org/carbondata/spark/package.scala
integration/spark/src/main/scala/org/carbondata/spark/util/CarbonScalaUtil.scala

Currently tinyint datatype is not supported in carbondata. This PR supports tinyint datatype.

[CARBONDATA-18]Supported tinyint datatype in carbondata

---

core/src/main/java/org/carbondata/core/carbon/path/CarbonTablePath.java

If storePath contains '-' like "incubator-carbon/store" , testcases fails and also potential bug to fail the queries.

[CARBONDATA-33]Fixed folder path issue when storePath contains '-'

---

hadoop/src/main/java/org/carbondata/hadoop/CarbonInputFormat.java

For carbondata the segment file is not splittable but it is splitting when the store is local. So we should avoid the file splitting for local store files.

[CARBONDATA-49]Fixed the query fails if big data is loaded to local store.

---

integration/spark/src/main/scala/org/apache/spark/sql/CarbonDictionaryDecoder.scala
integration/spark/src/main/scala/org/apache/spark/sql/optimizer/CarbonDecoderOptimizerHelper.scala
integration/spark/src/main/scala/org/apache/spark/sql/optimizer/CarbonOptimizer.scala
integration/spark/src/main/scala/org/carbondata/spark/CarbonFilters.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/allqueries/AllDataTypesTestCaseAggregate.scala

Queries using aggregates and sub queries like below are not working with Spark 1.6.2
`select Min(imei) from (select imei from table1 order by imei) t`.
This PR fixes this issue

Fixed aggregate queries with using subqueries in Spark 1.6.2

---

hadoop/src/main/java/org/carbondata/hadoop/util/ObjectSerializationUtil.java
integration/spark/src/main/scala/org/carbondata/spark/CarbonFilters.scala

Queries which have `IN` filter is not working from thriftserver, like 
`SELECT IMEI FROM TABLE1 WHERE IMEI IN ('1AA100074','1AA100075','1AA100077')`
This PR fixes it.

Fixed IN filter expression deserializing issue from thrift server

---

integration/spark/src/main/scala/org/apache/spark/sql/optimizer/CarbonOptimizer.scala
integration/spark/src/test/scala/org/carbondata/spark/testsuite/allqueries/AllDataTypesTestCaseAggregate.scala

Right join queries are not working with filters like below
`SELECT Carbon_automation.AMSize AS AMSize, Carbon_automation.ActiveCountry AS ActiveCountry, Carbon_automation.Activecity AS Activecity, SUM(Carbon_automation.gamePointId) AS Sum_gamePointId FROM ( SELECT AMSize, ActiveCountry, Activecity, gamePointId FROM (select * from Carbon_automation) SUB_QRY ) Carbon_automation RIGHT JOIN ( SELECT AMSize, ActiveCountry, Activecity, gamePointId FROM (select * from Carbon_automation) SUB_QRY ) Carbon_automation1 ON Carbon_automation.gamePointId = Carbon_automation1.gamePointId WHERE Carbon_automation.AMSize IN ("6RAM size","8RAM size") GROUP BY Carbon_automation.AMSize, Carbon_automation.ActiveCountry, Carbon_automation.Activecity ORDER BY Carbon_automation.AMSize ASC, …

Fixed right/left join query with filters are not working

---

pom.xml

Define doclint configuration on the maven-javadoc-plugin to be able to generate javadoc during release process.

[CARBONDATA-162] Fix javadoc generation

---

core/src/main/java/org/apache/carbondata/scan/filter/FilterExpressionProcessor.java
integration/spark/src/test/scala/org/apache/carbondata/spark/testsuite/filterexpr/TestAndEqualFilterEmptyOperandValue.scala

Affected Query syntax:
select * from Table Int_col='' and str_col='';

[CARBONDATA-195] Select query with AND filter failing for empty '' operand value of numeric column

---

core/pom.xml
pom.xml

fix below two warning when maven compile:
1. maven-shade-plugin omit version
2. [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.carbondata:carbondata-format:jar -> duplicate declaration of version ${project.version} @ line 99, column 17

[CARBONDATA-236] fix maven compile warning

---

integration/spark/src/main/scala/org/apache/carbondata/spark/util/DataTypeConverterUtil.scala
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala

Reason : Describe command will show DataType.simpleString in datatype column,
for LongType Spark DataType, simpleString is "bigint".
We are internally using long as name for bigint, which needs to be changed to bigint in Carbon DataTypes.

[CARBONDATA-249] As LongType.simpleString in spark is "bigint", Carbon will convert Long to BigInt

---

core/src/main/java/org/apache/carbondata/core/carbon/AbsoluteTableIdentifier.java
core/src/main/java/org/apache/carbondata/core/carbon/path/CarbonStorePath.java
examples/src/main/scala/org/apache/carbondata/examples/AllDictionaryExample.scala
examples/src/main/scala/org/apache/carbondata/examples/CarbonExample.scala
examples/src/main/scala/org/apache/carbondata/examples/ComplexTypeExample.scala
examples/src/main/scala/org/apache/carbondata/examples/DataFrameAPIExample.scala
examples/src/main/scala/org/apache/carbondata/examples/GenerateDictionaryExample.scala
examples/src/main/scala/org/apache/carbondata/examples/HadoopFileExample.scala
examples/src/main/scala/org/apache/carbondata/examples/PerfTest.scala
examples/src/main/scala/org/apache/carbondata/examples/util/ExampleUitls.scala
hadoop/src/main/java/org/apache/carbondata/hadoop/CarbonInputFormat.java
hadoop/src/main/java/org/apache/carbondata/hadoop/readsupport/impl/DictionaryDecodedReadSupportImpl.java
hadoop/src/main/java/org/apache/carbondata/hadoop/util/SchemaReader.java
hadoop/src/test/java/org/apache/carbondata/hadoop/ft/CarbonInputFormat_FT.java
hadoop/src/test/java/org/apache/carbondata/hadoop/ft/CarbonInputMapperTest.java
integration/spark/src/main/scala/org/apache/carbondata/spark/util/QueryPlanUtil.scala
integration/spark/src/main/scala/org/apache/spark/sql/CarbonDatasourceHadoopRelation.scala
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala

User should be able to use SparkContext.newAPIHadoopFile to read CarbonData files
For example:
```
val input = sc.newAPIHadoopFile(s"${cc.storePath}/default/carbon1",
classOf[CarbonInputFormat[Array[Object]]],
classOf[Void],
classOf[Array[Object]])
val result = input.map(x => x._2.toList).collect
result.foreach(x => println(x.mkString(", ")))
```
In this PR, the INPUT_DIR in CarbonInputFormat job configuration is changed to table path instead of store path, since sc.newAPIHadoopFile will set it to the first input parameter (`path` indicating the table path)

[CARBONDATA-257] Make CarbonData readable by SparkContext/MapReduce program

---

core/src/main/java/org/apache/carbondata/core/carbon/querystatistics/QueryStatistic.java
integration/spark/src/main/scala/org/apache/spark/sql/optimizer/CarbonOptimizer.scala

There are Some STATISTIC logs still present even though disable STATISTIC
Using QueryStatisticRecorder for STATISTIC log, so we can configurate it to print or not  uniformly,

[CARBONDATA-291] All STATISTIC log shouble be configurable

---

integration/spark/src/main/scala/org/apache/spark/sql/optimizer/CarbonOptimizer.scala

Compilation failed when using spark 1.6.2, because class not found: AggregateExpression
Once Removing the import "import org.apache.spark.sql.catalyst.expressions.aggregate._" will cause compilation failure when using Spark 1.6.2, in which AggregateExpression is moved to subpackage "aggregate". So neeed changing it back.
Thanks for you remind, @harperjiang

[CARBONDATA-310]Fixed compilation failure when using spark 1.6.2

---

docs/Quick-Start.md

This is too trivial so i didn't create JIRA task.
In Quick Start Guide there is use of string interpolation to create the file but while we are using it in SQL without using 's' before the string to apply string interpolation.
Manually tested it by run the string manipulation on carbon-spark-shell

trivial fix in documentation

---

integration/spark/src/main/scala/org/apache/spark/sql/CarbonCatalystOperators.scala
integration/spark/src/main/scala/org/apache/spark/sql/CarbonSqlParser.scala
integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonMetastoreCatalog.scala
integration/spark/src/main/scala/org/apache/spark/sql/hive/CarbonStrategies.scala
integration/spark/src/main/scala/org/apache/spark/sql/hive/execution/command/CarbonHiveCommands.scala
integration/spark/src/test/scala/org/apache/carbondata/spark/testsuite/deleteTable/TestDeleteTableNewDDL.scala

Issue : Currently drop database cascade command is restricted in Carbon
Solution : Implemented code to support below changes
1) Create DB folder in carbon store when user triggers Create database command
2) Removing DB folder from carbon store when user triggers Drop database command
3) Removing Tables & DB folder from carbon store when user triggers Drop database cascade command

[CARBONDATA-373] Drop Database Cascade command implementation.

---

core/src/main/java/org/apache/carbondata/scan/filter/resolver/resolverinfo/visitor/CustomTypeDictionaryVisitor.java

Problem: When time format is yyyy/mm/dd other than "-" filter query is not working , As in filter only "-" is allowed user need to give the filter value is "-" but as data loaded in in "/" filter is not working and returning 0 result. 
Soluntion: Problem is in filter we are taking default format but we need to take format used during data loaded while converting the filter values to surrogate key

[CARBONDATA-421]Time Stamp Filter issue with other than yyyy-mm-dd format

---

integration/spark-common/pom.xml
integration/spark2/pom.xml
pom.xml

To start spark2.0 integration with CarbonData, new modules need to be added:
1. spark-common, which will have all common classes for both spark1 and spark2 integration
2. spark2, which have carbon-spark2 integration
After the spark2 integration is done, CarbonData master branch should be enable to work with both spark1 and spark2. The target assembling is build by using profile, like:
- To build integration with spark1.5: use -Pspark-1.5
- To build integration with spark1.6: use -Pspark-1.6
- To build integration with spark2.0: use -Pspark-2.0

[CARBONDATA-441] Add modules for spark2 integration

---

integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark2/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala

InsertInto Feature:
If there is no partition in select sub-query dataframe , data loading will throw dataloadingexception
Solution:
The dataframe without partition, no need to do data loading.

[CARBONDATA-493]fix bug for insert into select from empty table 

---

core/src/main/java/org/apache/carbondata/scan/result/iterator/AbstractDetailQueryResultIterator.java

**Problem**
If query having filter and in btree jump when data ref node number is not zero query is throwing NPE 
Solution: currently we are checking != we need to check <

Fixed NPE issue in Query

---

integration/spark-common/src/main/scala/org/apache/spark/sql/hive/DistributionUtil.scala

Wrong number of executors requested when preferred locations are not obtained.
In case of groupby in subquery, we'll not get the preferred locations from the RDD as data is shuffled.
In such cases we need to use number of executors available.
This is applicable in case of dynamic executors

[CARBONDATA-581] Wrong number of executors requested when preferred locations are not obtained

---

integration/spark/src/main/scala/org/apache/spark/sql/CarbonDatasourceRelation.scala

using "new java.util.LinkedHashSet" instead of "new util.LinkedHashSet"

[CARBONDATA-568][Minor][Follow-Up] clean up code for carbon-core module

---

core/src/main/java/org/apache/carbondata/core/util/CarbonProperties.java
processing/src/test/java/org/apache/carbondata/carbon/datastore/BlockIndexStoreTest.java

**Problem:** Data file version is always taking latest version even if version is set to 1, This is because in carbon.properties we are calling valueof with string parameter and it is throwing illegalArugumentExcemption
**Solution:** Need to parse the string value to short and then call valueof method

[CARBONDATA-609]Fixed carbondata file version issue in carbon.properites

---

integration/spark-common-test/src/test/scala/org/apache/carbondata/spark/testsuite/badrecordloger/BadRecordLoggerTest.scala
integration/spark-common/src/main/scala/org/apache/spark/sql/catalyst/CarbonDDLSqlParser.scala

By default if no value is set by default BAD_RECORDS_ACTION will be initialized with FORCE.
But if the value for BAD_RECORDS_ACTION is set then the the value should be validated.

[CARBONDATA-634] Load Query options invalid values are not consistent behavior.

---

pom.xml

New repository http://136.243.101.176:9091/ is created, and url is added to pom file.
At the time of IPMC voting it can fetch from carbondata repository.
Admin can upload the format jar using following command.
First update maven settings.xml file,
```
<server>
<id>apache1</id>
<username>carbondata</username>
<password>******</password>
</server>
```
And use following command to upload format jar.
```
mvn  deploy:deploy-file -DpomFile=/home/root1/carbon/incubator-carbondata/format/pom.xml -Dfile=/home/root1/carbon/incubator-carbondata/core/target/carbondata-format-1.1.0-incubating.jar -DrepositoryId=apache1 -Durl=http://136.243.101.176:9091/repository/carbondata/
```

[CARBONDATA-702] Created carbondata repository and added repository URL to pom file.

---

core/src/main/java/org/apache/carbondata/core/constants/CarbonCommonConstants.java
core/src/main/java/org/apache/carbondata/core/locks/HdfsFileLock.java

It generates an invalid table metadata lock path when load data if run CarbonData on viewfs/federation. just since HdfsFileLock just check `hdfs://` URI but not `viewfs://`

[CARBONDATA-716] fix invalid hdfs lock path if config viewfs

---

hadoop/src/main/java/org/apache/carbondata/hadoop/util/CarbonInputSplitTaskInfo.java
integration/spark-common-test/src/test/resources/compaction/compactionIUD1.csv
integration/spark-common-test/src/test/resources/compaction/compactionIUD2.csv
integration/spark-common-test/src/test/resources/compaction/compactionIUD3.csv
integration/spark-common-test/src/test/resources/compaction/compactionIUD4.csv
integration/spark-common-test/src/test/scala/org/apache/carbondata/spark/testsuite/datacompaction/DataCompactionBlockletBoundryTest.scala
integration/spark-common-test/src/test/scala/org/apache/carbondata/spark/testsuite/datacompaction/DataCompactionCardinalityBoundryTest.scala
integration/spark-common/src/main/scala/org/apache/carbondata/spark/rdd/CarbonIUDMergerRDD.scala
integration/spark-common/src/main/scala/org/apache/carbondata/spark/rdd/CarbonMergerRDD.scala
integration/spark/src/main/scala/org/apache/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark/src/test/scala/org/apache/carbondata/spark/testsuite/datacompaction/DataCompactionTest.scala
integration/spark/src/test/scala/org/apache/carbondata/spark/testsuite/iud/IUDCompactionTestCases.scala

**Problem** : After Compaction record count mismatches with actual count. 
**Analysis** :The Partitioning method of compaction was wrong. In getPartition method of CarbonScanRDD.scala supposed to make a list all the blocks of all the segments that needs to be merged and then make the partition based on taskNo.  Then each partitioned list is given to each executor. But currently after partitioning the complete list of blocks are being send to each executor for merging. As each executors merging all the blocks of all the segments, multiple executors doubles the data. 
**Fix** : Fix the getPartition method logic to process proper list of blocks to executors.
Fix Horizontal Partitioning which merged with IUD.

[CARBONDATA-691] After Compaction records count are mismatched.

---

core/src/main/java/org/apache/carbondata/core/scan/filter/resolver/resolverinfo/visitor/DictionaryColumnVisitor.java

In can of exclude filter dictionary column DictionaryColumnVisitor is adding null value surrogate twice and because of this is not null query is giving wrong result

[CARBONDATA-770] Fixed null filter issue

---

integration/spark-common-test/src/test/scala/org/apache/carbondata/integration/spark/testsuite/emptyrow/TestEmptyRows.scala
integration/spark2/src/main/scala/org/apache/spark/sql/optimizer/CarbonLateDecodeRule.scala

if the data has null values then it should not count the data. But it is counting now as we are not decoding the data in case of count agg function. Now added decoder in case of count agg function as well.

[CARBONDATA-793] Fixed count with null values giving wrong values

---

core/src/main/java/org/apache/carbondata/core/util/ValueCompressionUtil.java
integration/spark-common-test/src/test/resources/testBigInt_boundary_value.csv
integration/spark-common-test/src/test/scala/org/apache/carbondata/integration/spark/testsuite/bigdecimal/TestBigInt.scala

When data contains long max and min values for a measure column with bigInt datatype, the delta compression selected is DATA_BYTE which is incorrect. For selecting the delta compression min value is decremented from max value and here the min value is negative, so it performs addition operation and goes out of long range. When a long value goes out of range it starts again from the long max negative value which results in wrong compression selection.
This leads to data loss and incorrect query results.

[CARBONDATA-797] Data loss for BigInt datatype if data contains long max and min values

---

core/src/main/java/org/apache/carbondata/core/scan/collector/impl/DictionaryBasedResultCollector.java
core/src/main/java/org/apache/carbondata/core/scan/collector/impl/RestructureBasedDictionaryResultCollector.java

Initialization of variables is moved to constructor. So that initialization is done only once on object creation instead of running a business logic.

[CARBONDATA-811] Refactor dictionary based result collector class.

---

core/src/main/java/org/apache/carbondata/core/util/path/CarbonTablePath.java
integration/spark-common-test/src/test/scala/org/apache/carbondata/spark/testsuite/dataload/TestDataLoadWithFileName.scala
processing/src/main/java/org/apache/carbondata/processing/mdkeygen/file/FileData.java
processing/src/main/java/org/apache/carbondata/processing/store/writer/AbstractFactDataWriter.java
processing/src/main/java/org/apache/carbondata/processing/store/writer/v1/CarbonFactDataWriterImplV1.java
processing/src/main/java/org/apache/carbondata/processing/store/writer/v2/CarbonFactDataWriterImplV2.java
processing/src/main/java/org/apache/carbondata/processing/store/writer/v3/CarbonFactDataWriterImplV3.java

The file_name stored in carbonindex is a local path which used on executor as temp dir 
```
/tmp/6937581525189542/0/default/carbon_v3/Fact/Part0/Segment_0/0/part-0-0_batchno0-0-1490345609845.carbondata
```
But I think we want to store the actual carbondata path like
```
part-0-0_batchno0-0-1490345609845.carbondata
```
I have already check this with @QiangCai.
cc @jackylk

[CARBONDATA-818] Make the file_name in carbonindex exactly

---

integration/spark-common/src/main/scala/org/apache/carbondata/spark/rdd/CarbonGlobalDictionaryRDD.scala

org.apache.carbondata.spark.rdd.CarbonGlobalDictionaryGenerateRDD find a bug:
code line 378-380
if (model.isFirstLoad && model.highCardIdentifyEnable
&& !model.isComplexes(split.index)
&& model.dimensions(split.index).isColumnar) {
model.dimensions(split.index).isColumnar must change to model.primDimensions(split.index).isColumnar because model.isComplexes.length may be != model.dimensions.length when create table use DICTIONARY_EXCLUDE or column datatype is complex

[CARBONDATA-828] CarbonGlobalDictionaryRDD model.isComplexes model.dimensions inconsistent

---

core/src/main/java/org/apache/carbondata/core/stats/QueryStatisticsRecorderImpl.java

Fix format of query statistics log, the corrected output will be:
```
+--------------+----------------+--------------------+----------------+--------------+--------------------+---------------+---------------+---------------+-----------+-----------+-----------+
|       task_id|load_blocks_time|load_dictionary_time|carbon_scan_time|carbon_IO_time| total_executor_time|scan_blocks_num|total_blocklets|valid_blocklets|total_pages|valid_pages|result_size|
+--------------+----------------+--------------------+----------------+--------------+--------------------+---------------+---------------+---------------+-----------+-----------+-----------+
|22035824523757|             2ms|                 2ms|         11448ms|         538ms|              2780ms|              1|              6| …
```

[CARBONDATA-827] Fix query stats format error

---

core/src/main/java/org/apache/carbondata/core/locks/HdfsFileLock.java
integration/spark2/src/main/scala/org/apache/spark/sql/hive/CarbonHiveMetadataUtil.scala

problem : Drop table command throwing table already exists exception
Solution: While invalidating the table from hive metastore, execute drop table command externally.

[CARBONDATA-873] Drop table command throwing table already exists exception

---

core/src/main/java/org/apache/carbondata/core/scan/filter/executer/RowLevelFilterExecuterImpl.java
core/src/main/java/org/apache/carbondata/core/scan/filter/resolver/RowLevelRangeFilterResolverImpl.java
core/src/main/java/org/apache/carbondata/core/util/ByteUtil.java
core/src/main/java/org/apache/carbondata/core/util/DataTypeUtil.java
integration/spark-common-test/src/test/scala/org/apache/carbondata/spark/testsuite/sortcolumns/TestSortColumns.scala
processing/src/main/java/org/apache/carbondata/processing/newflow/steps/CarbonRowDataWriterProcessorStepImpl.java

Fixed followed issues in sort_columns
1. for unsorted table, set taskExtension in CarbonRowDataWriterProcessorStepImpl, because one task will write more than one carbondata and carbonindex files.
2. modify getNoDictionaryRangeValues method of RowLevelRangeFilterResolverImpl to support all datatype
3. modify toBytes method of ByteUtil to support sorting of negative and positive number

fix sort_columns issue(12-dev)

---

integration/spark-common-test/src/test/scala/org/apache/carbondata/spark/testsuite/dataload/TestLoadDataFrame.scala
integration/spark/src/main/scala/org/apache/carbondata/spark/CarbonDataFrameWriter.scala
integration/spark2/src/main/scala/org/apache/spark/sql/CarbonDataFrameWriter.scala

Added options dictionary_include and dictionary_exclude in dataframe writer in spark 1.6
Fixed a bug in spark2 dataframe writer that cause an error when only dictionary_include is specified
Tested successfully in spark 2.6 / HDP 2.5

[CARBONDATA-888] Added options to include/exclude dictionary columns in dataframe writer

---

core/src/main/java/org/apache/carbondata/core/cache/dictionary/ManageDictionaryAndBTree.java
hadoop/src/main/java/org/apache/carbondata/hadoop/CacheAccessClient.java
hadoop/src/main/java/org/apache/carbondata/hadoop/CarbonInputFormat.java
integration/spark-common/src/main/scala/org/apache/carbondata/spark/rdd/AlterTableDropColumnRDD.scala
integration/spark2/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark2/src/test/scala/org/apache/spark/carbondata/CarbonDataSourceSuite.scala

Changes includes:
1. Support cleaning of BTree and dictionary instances when a table is being dropped.
2. Support clearing the access count for each segment immediately after block pruning rather then loading all the segments first and at lats clearing access count for all the segments together.

[CARBONDATA-914] Clear BTree and Dictionary instances from LRU cache on table drop

---

core/src/main/java/org/apache/carbondata/core/scan/filter/FilterUtil.java
core/src/main/java/org/apache/carbondata/core/scan/filter/executer/RowLevelFilterExecuterImpl.java
core/src/test/java/org/apache/carbondata/core/scan/filter/FilterUtilTest.java
integration/spark-common-test/src/test/resources/restructure/data6.csv
integration/spark2/src/test/scala/org/apache/spark/carbondata/restructure/vectorreader/AddColumnTestCases.scala

Probelme 1: When is null query is executed on newly added measure column, control goes to RowLevelFilterExecuterImpl class, where measure existence is checked. In case the measure is not found, bitset group is not getting populated with default values due to which that block is not returning any result.
Solution: When query is on a restructured block where newly added column does not exist, create the default bitset group so that based on default value existence default bitset group is created and results are returned based on that.
Problem2: While creating a default Bitset group in case of restructure array index out of bound exception is thrown.
Solution: If total number of records are exactly divisible by number of rows in each page then check for remainder > 0 to validate whether any …

[CARBONDATA-900] Is null query on a newly added measure column is not returning proper results

---

core/src/main/java/org/apache/carbondata/core/datastore/SegmentTaskIndexStore.java
core/src/main/java/org/apache/carbondata/core/mutate/CarbonUpdateUtil.java
core/src/main/java/org/apache/carbondata/core/statusmanager/SegmentStatusManager.java
examples/spark2/src/main/scala/org/apache/carbondata/examples/CompareTest.scala
hadoop/src/main/java/org/apache/carbondata/hadoop/CarbonInputSplit.java
integration/spark-common-test/src/test/scala/org/apache/carbondata/spark/testsuite/dataload/TestLoadDataFrame.scala
integration/spark-common/src/main/scala/org/apache/carbondata/spark/CarbonOption.scala
integration/spark2/src/main/scala/org/apache/spark/sql/CarbonDataFrameWriter.scala
processing/src/main/java/org/apache/carbondata/processing/merger/CarbonDataMergerUtil.java

User can specify SORT_COLUMNS option when using dataframe.write
For example:
```
input.write
.format("carbondata")
.option("tableName", carbonTableName(version))
.option("sort_columns", "c1, c2")
.mode(SaveMode.Overwrite)
.save()
```

[CARBONDATA-882] Add SORT_COLUMNS support in dataframe writer

---

core/src/main/java/org/apache/carbondata/core/constants/CarbonCommonConstants.java
core/src/main/java/org/apache/carbondata/core/util/ByteUtil.java
processing/src/main/java/org/apache/carbondata/processing/newflow/sort/unsafe/comparator/UnsafeRowComparator.java
processing/src/main/java/org/apache/carbondata/processing/newflow/sort/unsafe/holder/UnsafeInmemoryMergeHolder.java

There is an issue in unsafe merge sort as the comparisons gone wrong when the data is compared in unsafe without getting to heap. It is fixed now.

[CARBONDATA-960] Fix Unsafe merge sort issue

---

integration/spark2/src/main/scala/org/apache/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark2/src/main/scala/org/apache/spark/sql/CarbonDataFrameWriter.scala
integration/spark2/src/main/scala/org/apache/spark/sql/CarbonDatasourceHadoopRelation.scala
integration/spark2/src/main/scala/org/apache/spark/sql/CarbonDictionaryDecoder.scala
integration/spark2/src/main/scala/org/apache/spark/sql/CarbonEnv.scala
integration/spark2/src/main/scala/org/apache/spark/sql/CarbonSession.scala
integration/spark2/src/main/scala/org/apache/spark/sql/CarbonSource.scala
integration/spark2/src/main/scala/org/apache/spark/sql/execution/CarbonLateDecodeStrategy.scala
integration/spark2/src/main/scala/org/apache/spark/sql/execution/command/AlterTableCommands.scala
integration/spark2/src/main/scala/org/apache/spark/sql/execution/command/CarbonHiveCommands.scala
integration/spark2/src/main/scala/org/apache/spark/sql/execution/command/DDLStrategy.scala
integration/spark2/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark2/src/main/scala/org/apache/spark/sql/hive/CarbonSessionState.scala
integration/spark2/src/main/scala/org/apache/spark/util/AlterTableUtil.scala
integration/spark2/src/main/scala/org/apache/spark/util/CleanFiles.scala
integration/spark2/src/main/scala/org/apache/spark/util/Compaction.scala
integration/spark2/src/main/scala/org/apache/spark/util/DeleteSegmentByDate.scala
integration/spark2/src/main/scala/org/apache/spark/util/DeleteSegmentById.scala
integration/spark2/src/main/scala/org/apache/spark/util/ShowSegments.scala
integration/spark2/src/main/scala/org/apache/spark/util/TableAPIUtil.scala
integration/spark2/src/main/scala/org/apache/spark/util/TableLoader.scala

WIth multiple client connects in single thriftserver or different thriftserver uses same carbonstore, CarbonEnv object is static. When user performs alter operation in 1 beeline, latest updated schema information is not reflecting 2nd beeline.
Assume following concurrent operations
1) Beeline => select query on table1 (CarbonDatasourceRelation is cached)
2) spark-sql => add new column on table1 (this will refresh carbonMetastore available in carbonenv)
3) Beeline => Select query on table1 (This operation fails because it does not know whether the carbonMetastore is refreshed, hence cached CarbonDatasourceRelation will be returned which will not have newly added columns in schema fields)
Corrected this problem by changing CarbonEnv Object to class which will be instantiated for each …

[CARBONDATA-925]Changed CarbonEnv object to class and used sparksession to fetch the carbon catalog which will be used in that sparksession.

---

core/src/main/java/org/apache/carbondata/core/scan/collector/impl/AbstractScannedResultCollector.java

Problem: Bigdata Select query with where condition is failing
Solution : Remove precision and scale while applying big decimal measure value

[CARBONDATA-971] Select query with where condition is failing

---

integration/spark-common/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala

remove the first "encoders.remove(" from the below code in carbonTableSchema.scala
encoders.remove(encoders.remove(Encoding.DICTIONARY))

[CARBONDATA-975] remove unreasonable code

---

docs/installation-guide.md

Hello,
I followed the instruction on the page http://carbondata.incubator.apache.org/installation-guide.html and find an error in Installing and Configuring CarbonData on "Spark on YARN" Cluster part.
The value of “spark.driver.extraClassPath” should be “$SPARK_HOME/carbonlib/*” rather than “$SPARK_HOME/carbonlib/carbonlib/*”.
Thank you.

[CARBONDATA-990] fix instruction error

---

core/src/main/java/org/apache/carbondata/core/datastore/filesystem/AbstractDFSCarbonFile.java

- Remove variable fs, it may not be initialized when create a instance using AbstractDFSCarbonFile(FileStatus fileStatus).
- Fixed spelling mistakes.

[CARBONDATA-993]Remove confused variable fs & Fixed spelling mistakes

---

core/src/main/java/org/apache/carbondata/core/scan/collector/impl/RestructureBasedVectorResultCollector.java
integration/spark2/src/test/scala/org/apache/spark/carbondata/restructure/vectorreader/AddColumnTestCases.scala

Analysis: The date column being added had default value as Integer and it was being cast to long which caused the exception.
Solution: Add a condition to check the data type and cast appropriately.

[CARBONDATA-1011] Fixed cast exception for new column with date datatype

---

integration/spark2/src/main/scala/org/apache/spark/sql/execution/CastExpressionOptimization.scala

Problem : Cast Expression Optimization code was not working as expected due to wrong case statement. 
Fix: Fixed the case statements in Cast Expression optimization.

[CARBONDATA-805] Cast Optimization Case Statement Rectify

---

core/src/main/java/org/apache/carbondata/core/datastore/impl/FileFactory.java

When user provides relative local path as store path then there is an issue in path formation for update/delete feature. This PR fixes it.

[CARBONDATA-1022] Fixed relative store path issue while update and delete

---

integration/spark2/src/main/scala/org/apache/spark/sql/execution/command/DDLStrategy.scala
integration/spark2/src/test/scala/org/apache/spark/carbondata/restructure/AlterTableValidationTestCase.scala

Analysis: Database name was not being converted to lowercase which caused inconsistency in the rename process.
Solution: convert database and table name to lowercase

[CARBONDATA-1037] Changed dbname to lowercase in rename table

---

integration/spark-common-test/src/test/resources/IUD/bad_record.csv
integration/spark/src/main/scala/org/apache/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark/src/test/scala/org/apache/carbondata/spark/testsuite/iud/UpdateCarbonTableTestCase.scala

Problem: When bad records action is set to fail and any IUD operation… is executed and it fails due to bad records error message is not displayed correctly because of which user is not clear with the cause of update operation failure. Whereas in the same case in other operations like data load and insert into, if there is any failure due to bad record proper error message is displayed to the user for failure due to bad record.
Fix: Instead of forming own message get the executor failure message and send it to update operation as exception message.

[CARBONDATA-1045] Mismatch in message display with insert and load operation on failure due to bad records in update operation

---

core/src/main/java/org/apache/carbondata/core/constants/CarbonCommonConstants.java
core/src/main/java/org/apache/carbondata/core/dictionary/client/DictionaryClient.java
core/src/main/java/org/apache/carbondata/core/dictionary/generator/ServerDictionaryGenerator.java
core/src/main/java/org/apache/carbondata/core/dictionary/generator/key/DictionaryMessageType.java
core/src/main/java/org/apache/carbondata/core/dictionary/server/DictionaryServer.java
core/src/main/java/org/apache/carbondata/core/dictionary/server/DictionaryServerHandler.java
core/src/test/java/org/apache/carbondata/core/dictionary/client/DictionaryClientTest.java
integration/spark/src/main/scala/org/apache/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala
integration/spark2/src/main/scala/org/apache/carbondata/spark/rdd/CarbonDataRDDFactory.scala
integration/spark2/src/main/scala/org/apache/spark/sql/execution/command/carbonTableSchema.scala

In the earlier flow multiple instances of dictionary server were being created when parallel load requests were fired. This caused the later request to fail because a server was already running on the defined port.
Now only one instance of the dictionary server would be created on a load request and any consecutive requests would use the already created server.
Also removed the java future and instead we now use netty future for multithreading.

[CARBONDATA-773] Fixed multiple DictionaryServer instances issue

---

integration/spark-common-test/src/test/scala/org/apache/carbondata/spark/testsuite/dataload/TestBatchSortDataLoad.scala

There is a test case validation issue after the PR 899 has merged. That PR actually reduces the intermediate data size of keeping the data in respective correct data types. Because of it the current testcases got effected and created less batch files.

[CARBONDATA-1047] Corrected test case

---

core/src/main/java/org/apache/carbondata/core/scan/collector/impl/DictionaryBasedVectorResultCollector.java
core/src/main/java/org/apache/carbondata/core/scan/result/AbstractScannedResult.java

tupleId is an implicit column used in Update/Delete Implementation. 
When VectorReader is enabled, tupleId is not returning any output.

[CARBONDATA-1091] tupleId is not working with vector reader in spark2x

---

integration/spark-common/src/main/scala/org/apache/spark/sql/test/TestQueryExecutor.scala

Background: 
When run mvn  -Pspark-1.6 -Dspark.version=1.6.3 clean package, it will generate redundant
folders under integration model.
Solution:
add carbon store path in carbon property.

[CarbonData-1134] Generate redundant folders under integration model when run test cases with mvn command in spark1.6

---

core/src/main/java/org/apache/carbondata/core/datastore/SegmentTaskIndexStore.java
core/src/main/java/org/apache/carbondata/core/statusmanager/SegmentUpdateStatusManager.java
hadoop/src/main/java/org/apache/carbondata/hadoop/CarbonInputFormat.java
integration/presto/src/main/java/org/apache/carbondata/presto/impl/CarbonTableReader.java
integration/spark-common-test/src/test/scala/org/apache/carbondata/spark/testsuite/iud/HorizontalCompactionTestCase.scala
integration/spark-common/src/main/scala/org/apache/carbondata/spark/rdd/CarbonMergerRDD.scala
processing/src/main/java/org/apache/carbondata/processing/store/CarbonFactDataHandlerModel.java

IUD Performance Changes 
1. Get invalid blocks ony when there is a Update Performed in the Table. 
2. As UpdateVO is per segment basis no need to call it for each blocks. 
---

[CARBONDATA-1154] IUD Performance Changes

---

integration/presto/src/main/java/org/apache/carbondata/presto/PrestoCarbonVectorizedRecordReader.java
integration/presto/src/main/prestodb/org/apache/carbondata/presto/readers/SliceStreamReader.java
integration/presto/src/main/prestosql/org/apache/carbondata/presto/readers/SliceStreamReader.java

static method shouldn't be called by object, it should be call by class
There are some code smells in presto module
For example
1.Didn't add @OverRide for override method
2.magic number
3.variable Should Use LowerCamelCase
optimize some code smells in presto module
- No
- No

[ISSUE-4329] optimize some code smells in presto module

---

docs/supported-data-types-in-carbondata.md

Why is this PR needed?
CHAR and VARCHAR as String data types are no longer supported in Carbon. They should be deleted from doc's desc.
What changes were proposed in this PR?
CHAR and VARCHAR stop appearing as two String data types in doc.
Does this PR introduce any user interface change?
No
Is any new testcase added?
No

[CARBONDATA-4333][Doc] Update the declaration of supported String data types

---

core/src/main/java/org/apache/carbondata/core/reader/ThriftReader.java
core/src/main/java/org/apache/carbondata/core/util/CarbonUtil.java
core/src/main/java/org/apache/carbondata/core/writer/ThriftWriter.java
format/pom.xml
pom.xml

Why is this PR needed?
Thrift version 0.9.3 is not supported by new version of Linux
What changes were proposed in this PR?
Thrift library version is upgraded from 0.9.3 to 0.17.0
Does this PR introduce any user interface change?
No
Is any new testcase added?
No
Only thrift version is changed and compilation is fixed due to version upgrade.

[CARBONDATA-4349] Upgrade thrift version

---

integration/spark/pom.xml
pom.xml

[Issue-4352] Optimize geo module, the feature seems less be used

---

core/src/main/java/org/apache/carbondata/core/datastore/compression/SnappyCompressor.java

There is a security issue reported by the Apache Security Team. Calling Snappy.uncompress without length validation is subject to attack.
Add length validation before calling Snappy, modified all places in carbondata-core SnappyCompressor
- No
- No

[HOTFIX] Add length validation before calling Snappy uncompress
